import * as XLSX from "xlsx";
import { CollectionSummaryReportDto } from "../hooks/useCollectionReport";

export const exportCollectionReportToExcel = (
    reportData: CollectionSummaryReportDto,
    startDate: string,
    endDate: string
) => {
    const wb = XLSX.utils.book_new();

    // Sheet 1: KPI Summary
    const summaryWs = XLSX.utils.aoa_to_sheet([
        ["COLLECTION SHIFT SUMMARY"],
        ["Date Range:", `${startDate} to ${endDate}`],
        ["Generated By:", reportData.generatedBy || "System"],
        [],
        ["METRIC", "AMOUNT (PHP)"],
        ["Total Physical Cash", reportData.totalPhysicalCash],
        ["Total Checks", reportData.totalChecks],
        ["Total EWT Collected", reportData.totalEwt],
        ["Total Shortages (Dr)", reportData.totalShortages],
        ["Total Overages (Cr)", reportData.totalOverages],
        ["Net Variance", (reportData.totalOverages || 0) - (reportData.totalShortages || 0)],
        [],
        ["Total Invoices Cleared", reportData.totalInvoicesCleared],
        ["Total Memos Consumed", reportData.totalMemosConsumed],
        ["Total Returns Consumed", reportData.totalReturnsConsumed],
    ]);
    XLSX.utils.book_append_sheet(wb, summaryWs, "Summary");

    // Sheet 2: Invoices Settled
    const invoicesData = reportData.invoiceBreakdown.map(i => ({
        "Date": i.date,
        "Pouch Doc No": i.docNo,
        "Status": i.isPosted ? "POSTED" : "DRAFT",
        "Invoice No": i.invoiceNo,
        "Customer": i.customerName,
        "Payment Type": i.paymentType,
        "Amount Applied": i.amountApplied
    }));
    XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(invoicesData), "Invoices Settled");

    // Sheet 3: Checks
    const checksData = reportData.checkBreakdown.map(c => ({
        "Date": c.date,
        "Pouch Doc No": c.docNo,
        "Status": c.isPosted ? "POSTED" : "DRAFT",
        "Bank": c.bankName,
        "Check No": c.checkNo,
        "Customer / Remarks": c.customerName,
        "Amount": c.amount
    }));
    XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(checksData), "Checks Deposited");

    // Sheet 4: Variances
    const varianceData = reportData.varianceBreakdown.map(v => ({
        "Date": v.date,
        "Pouch Doc No": v.docNo,
        "Status": v.isPosted ? "POSTED" : "DRAFT",
        "Type": v.type,
        "Account Title": v.accountTitle,
        "Remarks": v.remarks,
        "Amount": v.amount
    }));
    XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(varianceData), "Variances");

    XLSX.writeFile(wb, `Collection_Report_${startDate}_to_${endDate}.xlsx`);
};