import * as XLSX from "xlsx";
import { CollectionSummaryReportDto } from "../hooks/useCollectionReport";

export const exportCollectionReportToExcel = (
    reportData: CollectionSummaryReportDto,
    startDate: string,
    endDate: string
) => {
    const wb = XLSX.utils.book_new();

    // Sheet 1: KPI Summary
    const summaryWs = XLSX.utils.aoa_to_sheet([
        ["COLLECTION SHIFT SUMMARY"],
        ["Date Range:", `${startDate} to ${endDate}`],
        ["Generated By:", reportData.generatedBy || "System"],
        [],
        ["METRIC", "AMOUNT (PHP)"],
        ["Total Physical Cash", reportData.globalCash],
        ["Total Checks", reportData.globalChecks],
        ["Total Shortages (Dr)", reportData.globalShortages],
        ["Total Overages (Cr)", reportData.globalOverages],
        ["Net Variance", (reportData.globalOverages || 0) - (reportData.globalShortages || 0)],
        [],
        ["Total Invoices Net Settled", reportData.globalNetInvoice],
    ]);
    XLSX.utils.book_append_sheet(wb, summaryWs, "Summary");

    // Sheet 2: Invoices Settled
    const invoicesData = reportData.pouches.flatMap(p =>
        p.invoices.map(i => ({
            "Date": p.date,
            "Pouch Doc No": p.docNo,
            "Status": p.isPosted ? "POSTED" : "DRAFT",
            "Invoice No": i.invoiceNo,
            "Customer": i.customerName,
            "Gross Amount": i.grossAmount,
            "Memo Amount": i.memoAmount,
            "Return Amount": i.returnAmount,
            "Net Amount": i.netAmount
        }))
    );
    XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(invoicesData), "Invoices Settled");

    // Sheet 3: Checks
    const checksData = reportData.pouches.flatMap(p =>
        p.checks.map(c => ({
            "Date": c.date || p.date,
            "Pouch Doc No": c.docNo || p.docNo,
            "Status": p.isPosted ? "POSTED" : "DRAFT",
            "Bank": c.bankName,
            "Check No": c.checkNo,
            "Customer / Remarks": c.customerName,
            "Amount": c.amount
        }))
    );
    XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(checksData), "Checks Deposited");

    // Sheet 4: Variances
    const varianceData = reportData.pouches.flatMap(p =>
        p.variances.map(v => ({
            "Date": p.date,
            "Pouch Doc No": v.docNo || p.docNo,
            "Status": p.isPosted ? "POSTED" : "DRAFT",
            "Type": v.type,
            "Account Title": v.accountTitle,
            "Remarks": v.remarks,
            "Amount": v.amount
        }))
    );
    XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(varianceData), "Variances");

    XLSX.writeFile(wb, `Collection_Report_${startDate}_to_${endDate}.xlsx`);
};