import * as XLSX from "xlsx";
import { CollectionSummaryReportDto } from "../hooks/useCollectionReport";

const displayIdentifier = (value?: string | null) => value?.trim() || "\u2014";
const displayCustomer = (value?: string | null) => {
    const customer = value?.trim();
    return customer && !/^chk-/i.test(customer) ? customer : "N/A";
};

export const exportCollectionReportToExcel = (
    reportData: CollectionSummaryReportDto,
    startDate: string,
    endDate: string
) => {
    const wb = XLSX.utils.book_new();
    const totalAssets = (reportData.globalCash || 0) + (reportData.globalChecks || 0);

    const summaryWs = XLSX.utils.aoa_to_sheet([
        ["COLLECTION SHIFT SUMMARY"],
        ["Date Range:", `${startDate} to ${endDate}`],
        ["Generated By:", reportData.generatedBy || "System"],
        [],
        ["METRIC", "AMOUNT (PHP)"],
        ["Total Physical Cash", reportData.globalCash],
        ["Total Checks", reportData.globalChecks],
        ["Total Assets / Total Remittance", totalAssets],
        ["Total Shortages (Dr)", reportData.globalShortages],
        ["Total Overages (Cr)", reportData.globalOverages],
        ["Net Variance", (reportData.globalOverages || 0) - (reportData.globalShortages || 0)],
        [],
        ["Total Invoices Net Settled", reportData.globalNetInvoice],
    ]);
    XLSX.utils.book_append_sheet(wb, summaryWs, "Summary");

    const invoicesData = reportData.pouches.flatMap((pouch) =>
        pouch.invoices.map((invoice) => ({
            Date: pouch.date,
            "Pouch Doc No": pouch.docNo,
            Status: pouch.isPosted ? "POSTED" : "DRAFT",
            "Invoice No": invoice.invoiceNo,
            Customer: invoice.customerName,
            "Actual Invoice Total": invoice.actualInvoiceTotal ?? invoice.invoiceTotal,
            "Amount Applied": invoice.grossAmount,
            "Remaining Balance": invoice.remainingBalance,
            "Memo Amount": invoice.memoAmount,
            "Return Amount": invoice.returnAmount,
            "Net Amount": invoice.netAmount,
        }))
    );
    XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(invoicesData), "Invoices Settled");

    const checksData = reportData.pouches.flatMap((pouch) =>
        pouch.checks.map((check) => ({
            Date: check.date || pouch.date,
            "Pouch Doc No": check.docNo || pouch.docNo,
            Status: pouch.isPosted ? "POSTED" : "DRAFT",
            Bank: check.bankName,
            "Check No": check.checkNo,
            "Check Date": check.chequeDate || "N/A",
            Customer: displayCustomer(check.customerName),
            Amount: check.amount,
        }))
    );
    XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(checksData), "Checks Deposited");

    const varianceData = reportData.pouches.flatMap((pouch) =>
        pouch.variances.map((variance) => ({
            Date: pouch.date,
            "Pouch Doc No": variance.docNo || pouch.docNo,
            Status: pouch.isPosted ? "POSTED" : "DRAFT",
            Type: variance.type,
            Customer: displayIdentifier(variance.customerName),
            "Invoice No": displayIdentifier(variance.invoiceNo),
            "Account Title": variance.accountTitle,
            Remarks: variance.remarks,
            Amount: variance.amount,
        }))
    );
    XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(varianceData), "Variances");

    XLSX.writeFile(wb, `Collection_Report_${startDate}_to_${endDate}.xlsx`);
};
