import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { format } from "date-fns";
import { CollectionSummaryReportDto } from "../hooks/useCollectionReport";
import type { CompanyProfile } from "../../company-profile";
import {
    COLLECTION_PDF_MARGIN,
    drawCollectionPdfHeader,
    getCollectionPdfTableWidth,
} from "./pdf-header";

const formatAmount = (value?: number | null) =>
    "P " + Number(value ?? 0).toLocaleString(undefined, { minimumFractionDigits: 2 });
const displayIdentifier = (value?: string | null) => value?.trim() || "\u2014";
const displayCustomer = (value?: string | null) => {
    const customer = value?.trim();
    return customer && !/^chk-/i.test(customer) ? customer : "N/A";
};
const formatShortDate = (value?: string | null) => value ? format(new Date(value), "MM/dd") : "\u2014";

export const generateCollectionPDF = (
    reportData: CollectionSummaryReportDto,
    startDate: string,
    endDate: string,
    companyProfile: CompanyProfile | null,
) => {
    const doc = new jsPDF("p", "pt", "a4");
    const pageWidth = doc.internal.pageSize.getWidth();
    const tableWidth = getCollectionPdfTableWidth(doc);
    let currentY = drawCollectionPdfHeader(
        doc,
        companyProfile,
        "Treasury Department - Collection Shift Summary",
    );
    doc.setFontSize(9);
    doc.text("Date Range: " + startDate + " to " + endDate, 40, currentY);
    doc.text("Generated By: " + (reportData.generatedBy || "System"), pageWidth - 40, currentY, { align: "right" });
    doc.text("Printed On: " + format(new Date(), "yyyy-MM-dd HH:mm"), pageWidth - 40, currentY + 15, { align: "right" });

    currentY += 35;
    const netVariance = (reportData.globalOverages || 0) - (reportData.globalShortages || 0);
    const totalAssets = (reportData.globalCash || 0) + (reportData.globalChecks || 0);
    const totalEwt = reportData.pouches.reduce(
        (total, pouch) => total + pouch.variances
            .filter((variance) => variance.type.toLowerCase().includes("ewt"))
            .reduce((sum, variance) => sum + variance.amount, 0),
        0
    );
    const totalMemos = reportData.pouches.reduce((total, pouch) => total + pouch.totalMemos, 0);
    const totalReturns = reportData.pouches.reduce((total, pouch) => total + pouch.totalReturns, 0);

    autoTable(doc, {
        startY: currentY,
        head: [["Metric", "Amount (PHP)"]],
        body: [
            ["Total Physical Cash", formatAmount(reportData.globalCash)],
            ["Total Checks", formatAmount(reportData.globalChecks)],
            ["Total Assets / Total Remittance", formatAmount(totalAssets)],
            ["Total EWT Collected", formatAmount(totalEwt)],
            ["Net Variance", (netVariance < 0 ? "-" : "") + formatAmount(Math.abs(netVariance))],
            ["Total Invoices Net Settled", formatAmount(reportData.globalNetInvoice)],
            ["Total Memos Consumed", formatAmount(totalMemos)],
            ["Total Returns Consumed", formatAmount(totalReturns)],
        ],
        theme: "plain",
        styles: { fontSize: 9, cellPadding: 4 },
        headStyles: { fillColor: [240, 240, 240], textColor: [0, 0, 0], fontStyle: "bold" },
        columnStyles: { 0: { fontStyle: "bold" }, 1: { halign: "right", fontStyle: "bold" } },
        margin: { left: COLLECTION_PDF_MARGIN, right: COLLECTION_PDF_MARGIN },
        tableWidth,
    });

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    currentY = (doc as any).lastAutoTable.finalY + 30;
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.text("Accounts Settled (Invoices & Credits)", 40, currentY);
    currentY += 10;

    const invoiceRows = reportData.pouches.flatMap((pouch) =>
        pouch.invoices.map((invoice) => [
            formatShortDate(pouch.date),
            pouch.docNo,
            pouch.isPosted ? "POSTED" : "DRAFT",
            invoice.invoiceNo,
            invoice.customerName,
            formatAmount(invoice.actualInvoiceTotal ?? invoice.invoiceTotal),
            formatAmount(invoice.invoiceTotal),
            formatAmount(invoice.grossAmount),
            formatAmount(invoice.remainingBalance),
        ])
    );

    autoTable(doc, {
        startY: currentY,
        head: [["Date", "Doc No", "Status", "Invoice No", "Customer", "Gross Invoice Total", "Net Receivable", "Amount Applied", "Remaining Balance"]],
        body: invoiceRows,
        theme: "grid",
        headStyles: { fillColor: [46, 204, 113] },
        styles: { fontSize: 7 },
        columnStyles: {
            5: { halign: "right", fontStyle: "bold" },
            6: { halign: "right", fontStyle: "bold" },
            7: { halign: "right", fontStyle: "bold" },
            8: { halign: "right", fontStyle: "bold" },
        },
        margin: { left: COLLECTION_PDF_MARGIN, right: COLLECTION_PDF_MARGIN },
        tableWidth,
    });

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    currentY = (doc as any).lastAutoTable.finalY + 30;
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.text("Deposits (Checks)", 40, currentY);
    currentY += 10;

    const checkRows = reportData.pouches.flatMap((pouch) =>
        pouch.checks.map((check) => [
            formatShortDate(check.date || pouch.date),
            check.docNo || pouch.docNo,
            pouch.isPosted ? "POSTED" : "DRAFT",
            check.bankName,
            check.checkNo,
            formatShortDate(check.chequeDate),
            displayCustomer(check.customerName),
            formatAmount(check.amount),
        ])
    );

    autoTable(doc, {
        startY: currentY,
        head: [["Date", "Doc No", "Status", "Bank", "Check No", "Check Date", "Customer", "Amount"]],
        body: checkRows,
        theme: "grid",
        headStyles: { fillColor: [52, 152, 219] },
        styles: { fontSize: 8 },
        columnStyles: { 7: { halign: "right", fontStyle: "bold" } },
        margin: { left: COLLECTION_PDF_MARGIN, right: COLLECTION_PDF_MARGIN },
        tableWidth,
    });

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    currentY = (doc as any).lastAutoTable.finalY + 30;
    const flatVariances = reportData.pouches.flatMap((pouch) =>
        pouch.variances.map((variance) => ({
            ...variance,
            date: pouch.date,
            docNo: variance.docNo || pouch.docNo,
            isPosted: pouch.isPosted,
        }))
    );

    if (flatVariances.length > 0) {
        doc.setFontSize(11);
        doc.setFont("helvetica", "bold");
        doc.text("Adjustments / Variances", 40, currentY);
        currentY += 10;

        const varianceRows = flatVariances.map((variance) => [
            formatShortDate(variance.date),
            variance.docNo,
            variance.isPosted ? "POSTED" : "DRAFT",
            variance.type,
            displayIdentifier(variance.customerName),
            displayIdentifier(variance.invoiceNo),
            variance.accountTitle,
            variance.remarks,
            formatAmount(variance.amount),
        ]);

        autoTable(doc, {
            startY: currentY,
            head: [["Date", "Doc No", "Status", "Type", "Customer", "Invoice No", "Account", "Remarks", "Amount"]],
            body: varianceRows,
            theme: "grid",
            headStyles: { fillColor: [155, 89, 182] },
            styles: { fontSize: 6.5 },
            columnStyles: { 8: { halign: "right", fontStyle: "bold" } },
            margin: { left: COLLECTION_PDF_MARGIN, right: COLLECTION_PDF_MARGIN },
            tableWidth,
        });
    }

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const pageCount = (doc as any).internal.getNumberOfPages();
    for (let page = 1; page <= pageCount; page++) {
        doc.setPage(page);
        doc.setFontSize(8);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(150);
        doc.text("Page " + page + " of " + pageCount, pageWidth / 2, doc.internal.pageSize.getHeight() - 20, { align: "center" });
    }

    doc.save("Collection_Report_" + startDate + "_to_" + endDate + ".pdf");
};
