import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { format } from "date-fns";
import { CollectionSummaryReportDto } from "../hooks/useCollectionReport";

export const generateCollectionPDF = (
    reportData: CollectionSummaryReportDto,
    startDate: string,
    endDate: string
) => {
    // Initialize A4 document (Portrait, Points)
    const doc = new jsPDF("p", "pt", "a4");
    const pageWidth = doc.internal.pageSize.getWidth();
    let currentY = 40;

    // --- 1. HEADER (Letterhead) ---
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text("MEN2 MARKETING CORPORATION", pageWidth / 2, currentY, { align: "center" });

    currentY += 20;
    doc.setFontSize(12);
    doc.setFont("helvetica", "normal");
    doc.text("Treasury Department - Collection Shift Summary", pageWidth / 2, currentY, { align: "center" });

    currentY += 30;
    doc.setFontSize(9);
    doc.text(`Date Range: ${startDate} to ${endDate}`, 40, currentY);
    doc.text(`Generated By: ${reportData.generatedBy || "System"}`, pageWidth - 40, currentY, { align: "right" });
    doc.text(`Printed On: ${format(new Date(), "yyyy-MM-dd HH:mm")}`, pageWidth - 40, currentY + 15, { align: "right" });

    currentY += 35;

    // --- 2. KPI SUMMARY BLOCK ---
    const netVariance = (reportData.totalOverages || 0) - (reportData.totalShortages || 0);

    autoTable(doc, {
        startY: currentY,
        head: [["Asset Type", "Amount (PHP)"], ["Liabilities Cleared", "Amount (PHP)"]],
        body: [
            ["Total Physical Cash", `P ${reportData.totalPhysicalCash.toLocaleString(undefined, {minimumFractionDigits: 2})}`],
            ["Total Checks", `P ${reportData.totalChecks.toLocaleString(undefined, {minimumFractionDigits: 2})}`],
            ["Total EWT Collected", `P ${reportData.totalEwt.toLocaleString(undefined, {minimumFractionDigits: 2})}`],
            ["Net Variance", `${netVariance < 0 ? '-' : ''}P ${Math.abs(netVariance).toLocaleString(undefined, {minimumFractionDigits: 2})}`],
            ["", ""],
            ["Total Invoices Cleared", `P ${reportData.totalInvoicesCleared.toLocaleString(undefined, {minimumFractionDigits: 2})}`],
            ["Total Memos Consumed", `P ${reportData.totalMemosConsumed.toLocaleString(undefined, {minimumFractionDigits: 2})}`],
            ["Total Returns Consumed", `P ${reportData.totalReturnsConsumed.toLocaleString(undefined, {minimumFractionDigits: 2})}`]
        ],
        theme: "plain",
        styles: { fontSize: 9, cellPadding: 4 },
        headStyles: { fillColor: [240, 240, 240], textColor: [0, 0, 0], fontStyle: "bold" },
        columnStyles: { 0: { fontStyle: 'bold' }, 1: { halign: 'right', fontStyle: 'bold' } },
        margin: { left: 40, right: pageWidth / 2 + 20 },
        tableWidth: 'wrap'
    });

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    currentY = (doc as any).lastAutoTable.finalY + 30;

    // --- 3. ACCOUNTS SETTLED TABLE ---
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.text("Accounts Settled (Invoices & Credits)", 40, currentY);

    currentY += 10;
    const invoiceRows = reportData.invoiceBreakdown.map(i => [
        format(new Date(i.date), "MM/dd"),
        i.docNo,
        i.isPosted ? "POSTED" : "DRAFT",
        i.invoiceNo,
        i.customerName,
        i.paymentType,
        i.amountApplied.toLocaleString(undefined, {minimumFractionDigits: 2})
    ]);

    autoTable(doc, {
        startY: currentY,
        head: [["Date", "Doc No", "Status", "Invoice No", "Customer", "Type", "Amount"]],
        body: invoiceRows,
        theme: "grid",
        headStyles: { fillColor: [46, 204, 113] }, // Emerald Green
        styles: { fontSize: 8 },
        columnStyles: { 6: { halign: 'right', fontStyle: 'bold' } },
        margin: { left: 40, right: 40 },
    });

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    currentY = (doc as any).lastAutoTable.finalY + 30;

    // --- 4. CHECKS DEPOSITED TABLE ---
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.text("Deposits (Checks)", 40, currentY);

    currentY += 10;
    const checkRows = reportData.checkBreakdown.map(c => [
        format(new Date(c.date), "MM/dd"),
        c.docNo,
        c.isPosted ? "POSTED" : "DRAFT",
        c.bankName,
        c.checkNo,
        c.customerName,
        c.amount.toLocaleString(undefined, {minimumFractionDigits: 2})
    ]);

    autoTable(doc, {
        startY: currentY,
        head: [["Date", "Doc No", "Status", "Bank", "Check No", "Customer / Remarks", "Amount"]],
        body: checkRows,
        theme: "grid",
        headStyles: { fillColor: [52, 152, 219] }, // Blue
        styles: { fontSize: 8 },
        columnStyles: { 6: { halign: 'right', fontStyle: 'bold' } },
        margin: { left: 40, right: 40 },
    });

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    currentY = (doc as any).lastAutoTable.finalY + 30;

    // --- 5. VARIANCES TABLE ---
    if (reportData.varianceBreakdown.length > 0) {
        doc.setFontSize(11);
        doc.setFont("helvetica", "bold");
        doc.text("Adjustments / Variances", 40, currentY);

        currentY += 10;
        const varRows = reportData.varianceBreakdown.map(v => [
            format(new Date(v.date), "MM/dd"),
            v.docNo,
            v.isPosted ? "POSTED" : "DRAFT",
            v.type,
            v.accountTitle,
            v.remarks,
            v.amount.toLocaleString(undefined, {minimumFractionDigits: 2})
        ]);

        autoTable(doc, {
            startY: currentY,
            head: [["Date", "Doc No", "Status", "Type", "Account", "Remarks", "Amount"]],
            body: varRows,
            theme: "grid",
            headStyles: { fillColor: [155, 89, 182] }, // Purple
            styles: { fontSize: 8 },
            columnStyles: { 6: { halign: 'right', fontStyle: 'bold' } },
            margin: { left: 40, right: 40 },
        });
    }

    // --- 6. PAGINATION (Page X of Y footer) ---
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const pageCount = (doc as any).internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(150);
        doc.text(
            `Page ${i} of ${pageCount}`,
            pageWidth / 2,
            doc.internal.pageSize.getHeight() - 20,
            { align: "center" }
        );
    }

    // --- 7. EXPORT ---
    // Either save it directly:
    doc.save(`Collection_Report_${startDate}_to_${endDate}.pdf`);

    // OR output to a new tab/blob for preview:
    // window.open(doc.output('bloburl'), '_blank');
};