import { TrialBalanceAccount, JournalEntryLine } from "./types";

export const MOCK_ACCOUNTS: TrialBalanceAccount[] = [
  {
    id: "1",
    code: "1020",
    title: "Cash in Bank",
    branch: "Cebu",
    division: "Finance",
    department: "Treasury",
    module: "Journal Entry",
    status: "Posted",
    date: "2026-03-31",
    debit: -15000,
    credit: 0,
    balance: -15000,
    reviewFlag: "critical", // Negative cash is critical
    accountType: "Asset",
  },
  {
    id: "2",
    code: "2100",
    title: "Accounts Payable",
    branch: "Cebu",
    division: "Finance",
    department: "Payables",
    module: "AP",
    status: "Posted",
    date: "2026-03-31",
    debit: 0,
    credit: 520000,
    balance: 520000,
    reviewFlag: "normal",
    accountType: "Liability",
  },
  {
    id: "3",
    code: "4100",
    title: "Sales Revenue",
    branch: "Davao",
    division: "Sales",
    department: "Field Sales",
    module: "Sales",
    status: "Posted",
    date: "2026-03-20",
    debit: 0,
    credit: 1200000,
    balance: 1200000,
    reviewFlag: "normal",
    accountType: "Revenue",
  },
  {
    id: "4",
    code: "1010",
    title: "Cash on Hand",
    branch: "Manila",
    division: "Finance",
    department: "Treasury",
    module: "Journal Entry",
    status: "Posted",
    date: "2026-03-31",
    debit: 125000,
    credit: 0,
    balance: 125000,
    reviewFlag: "high", // High value for manual verification
    accountType: "Asset",
  },
];

export const MOCK_JOURNAL_LINES: JournalEntryLine[] = [
  {
    id: "JE-2026-001",
    date: "2026-03-15",
    description: "Monthly Office Rent Payment",
    debit: 0,
    credit: 45000,
    source: "AP Module",
    postedBy: "John Doe",
  },
  {
    id: "JE-2026-002",
    date: "2026-03-18",
    description: "Customer Payment - INV-882",
    debit: 120000,
    credit: 0,
    source: "AR Module",
    postedBy: "Jane Smith",
  },
  {
    id: "JE-2026-003",
    date: "2026-03-25",
    description: "Initial Capital Investment",
    debit: 500000,
    credit: 0,
    source: "Manual Entry",
    postedBy: "Admin",
  },
];
