import ExcelJS from "exceljs";
import { saveAs } from "file-saver";

import type { MatrixRow } from "../types";
import type { PriceTypeRef, UnitRef } from "../../shared/supplier-batch/flattenPrintMatrix";
import { buildUnitColumns } from "../../shared/supplier-batch/flattenPrintMatrix";
import {
    styleSupplierBatchWorksheet,
    isProposedColumnHeader,
} from "../../shared/supplier-batch/supplierBatchExcelStyles";

const COL_PRODUCT_ID = "Product ID";
const COL_PRODUCT_CODE = "Product Code";
const COL_BARCODE = "Barcode";
const COL_PRODUCT_NAME = "Product Name";
const COL_GROUP_ID = "Group ID";
const COL_PARENT_ID = "Parent ID";

const IDENTITY_HEADERS = [
    COL_PRODUCT_ID,
    COL_PRODUCT_CODE,
    COL_BARCODE,
    COL_PRODUCT_NAME,
    COL_GROUP_ID,
    COL_PARENT_ID,
] as const;

function sortPriceTypes(priceTypes: PriceTypeRef[]): PriceTypeRef[] {
    return [...priceTypes].sort((a, b) => {
        const aSort = Number(a.sort ?? Number.MAX_SAFE_INTEGER);
        const bSort = Number(b.sort ?? Number.MAX_SAFE_INTEGER);
        return aSort - bSort || String(a.price_type_name ?? "").localeCompare(String(b.price_type_name ?? ""));
    });
}

function currentListCostHeader(unitLabel: string) {
    return `Current List Cost (${unitLabel})`;
}

function proposedListCostHeader(unitLabel: string) {
    return `Proposed List Cost (${unitLabel})`;
}

function priceCurrentHeader(priceType: PriceTypeRef, unitLabel: string) {
    return `Price ${String(priceType.price_type_name ?? `#${priceType.price_type_id}`).trim()} Current (${unitLabel})`;
}

function priceProposedHeader(priceType: PriceTypeRef, unitLabel: string) {
    return `Price ${String(priceType.price_type_name ?? `#${priceType.price_type_id}`).trim()} Proposed (${unitLabel})`;
}

export async function exportProductPrintablesExcel(args: {
    matrixRows: MatrixRow[];
    priceTypes: PriceTypeRef[];
    units: UnitRef[];
    filterSummary: string;
    userName: string;
    includeProposedColumns?: boolean;
}): Promise<void> {
    const {
        matrixRows,
        priceTypes,
        units,
        filterSummary,
        userName,
        includeProposedColumns = false,
    } = args;

    if (matrixRows.length === 0) return;

    const sortedPriceTypes = sortPriceTypes(priceTypes);
    const unitColumns = buildUnitColumns(matrixRows as Parameters<typeof buildUnitColumns>[0], units);
    const generatedAt = new Date();

    const wb = new ExcelJS.Workbook();
    const ws = wb.addWorksheet("Masterlist");

    // Meta rows (2-column [label, value] format matching PRC style)
    ws.addRow(["Report", "Product Printables Masterlist"]);
    ws.addRow(["Generated", `${generatedAt.toLocaleDateString("en-PH")} ${generatedAt.toLocaleTimeString("en-PH")}`]);
    ws.addRow(["Generated by", userName || "System User"]);
    if (filterSummary) {
        ws.addRow(["Filters", filterSummary.replace(/\n/g, "; ")]);
    } else {
        ws.addRow(["Filters", "All Products"]);
    }
    ws.addRow([]); // blank separator row

    // Headers
    const headers = [
        ...IDENTITY_HEADERS,
        ...unitColumns.flatMap((unit) =>
            includeProposedColumns
                ? [currentListCostHeader(unit.label), proposedListCostHeader(unit.label)]
                : [currentListCostHeader(unit.label)],
        ),
        ...sortedPriceTypes.flatMap((priceType) =>
            unitColumns.flatMap((unit) =>
                includeProposedColumns
                    ? [priceCurrentHeader(priceType, unit.label), priceProposedHeader(priceType, unit.label)]
                    : [priceCurrentHeader(priceType, unit.label)],
            ),
        ),
    ];

    const headerRow = ws.addRow(headers);
    const headerRowNumber = headerRow.number;
    const totalColumns = headers.length;

    // Data rows
    for (const row of matrixRows) {
        const display = row.display;
        const values: Array<string | number | null> = [
            display.product_id,
            display.product_code ?? "",
            display.barcode ?? "",
            display.product_name,
            row.group_id,
            display.parent_id ?? "",
        ];

        for (const unit of unitColumns) {
            const variant = row.variantsByUnitId[unit.unitId];
            const current = variant?.tiers.LIST ?? variant?.product.cost_per_unit ?? null;
            values.push(variant && current != null ? Number(current) : null);
            if (includeProposedColumns) values.push(null);
        }

        for (const priceType of sortedPriceTypes) {
            for (const unit of unitColumns) {
                const variant = row.variantsByUnitId[unit.unitId];
                const current = variant?.tiers[String(priceType.price_type_id)] ?? null;
                values.push(variant ? current : null);
                if (includeProposedColumns) values.push(null);
            }
        }

        ws.addRow(values.map((v) => v === null ? "" : v));
    }

    const dataStartRowNumber = headerRowNumber + 1;

    // Column widths (shared styling expects specific widths)
    ws.getColumn(1).width = 12;
    ws.getColumn(2).width = 14;
    ws.getColumn(3).width = 16;
    ws.getColumn(4).width = 36;
    ws.getColumn(5).width = 10;
    ws.getColumn(6).width = 10;
    for (let c = 7; c <= headers.length; c++) {
        ws.getColumn(c).width = 18;
    }

    // Number formatting for price columns
    const identityColCount = IDENTITY_HEADERS.length;
    for (let r = dataStartRowNumber; r <= ws.rowCount; r++) {
        for (let c = identityColCount + 1; c <= headers.length; c++) {
            ws.getCell(r, c).numFmt = "#,##0.00";
        }
    }

    // Proposed column indexes (1-based) for shared styling
    const proposedColumnIndexes: number[] = [];
    for (let c = 0; c < headers.length; c++) {
        if (isProposedColumnHeader(headers[c])) {
            proposedColumnIndexes.push(c + 1);
        }
    }

    // Apply the same styling pipeline used by the PRC supplier export
    styleSupplierBatchWorksheet({
        sheet: ws,
        headerRowNumber,
        totalColumns,
        dataStartRowNumber,
        proposedColumnIndexes,
        // instructionStartRowNumber intentionally omitted (read-only export)
    });

    // Re-style the first meta row as a bold title
    const titleRow = ws.getRow(1);
    ws.mergeCells(1, 1, 1, Math.min(2, totalColumns));
    titleRow.getCell(1).value = "Product Printables Masterlist";
    titleRow.getCell(1).font = { name: "Calibri", bold: true, size: 14 };
    titleRow.getCell(1).alignment = { vertical: "middle" };
    titleRow.height = 28;

    const buffer = await wb.xlsx.writeBuffer();
    const blob = new Blob([buffer], { type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" });
    saveAs(blob, `Masterlist_${generatedAt.toISOString().split("T")[0]}.xlsx`);
}
